// The story. Each era has an authored chapter and a pool of discoveries for
// the ruins ticker. After the first cycle the ruins become personal: cycle
// discoveries join the ticker, and after the ending the message you chose is
// found carved into later civilizations' ruins.

export const CHAPTERS = {
  "1": {
    "title": "A fire among the ruins",
    "discovery": "The first foundations follow the exact outline of your ship.",
    "landmark": "Signal cairn",
    "color": "#d8ac70"
  },
  "2": {
    "title": "The machines below",
    "discovery": "The machines contain maintenance notes in your handwriting.",
    "landmark": "Memory foundry",
    "color": "#e89a72"
  },
  "3": {
    "title": "Someone is listening",
    "discovery": "The last transmission includes tomorrow’s date.",
    "landmark": "Listening array",
    "color": "#7acabc"
  },
  "4": {
    "title": "A harbor in the dark",
    "discovery": "An empty docking berth bears the name of your ship.",
    "landmark": "Orbital harbor",
    "color": "#8bbce4"
  },
  "5": {
    "title": "Homes beyond home",
    "discovery": "Under each new home is the hearth of an older one.",
    "landmark": "Living sanctuary",
    "color": "#9bd29a"
  },
  "6": {
    "title": "Roads through silence",
    "discovery": "The beacons answer in the order you planned to visit them.",
    "landmark": "Wayfinder beacon",
    "color": "#a4a2ea"
  },
  "7": {
    "title": "Borrowed sunlight",
    "discovery": "One collector contains a handprint that fits yours.",
    "landmark": "Solar crown",
    "color": "#edca76"
  },
  "8": {
    "title": "The right to remember",
    "discovery": "Every delegate brings a different version of the same history.",
    "landmark": "Hall of voices",
    "color": "#dfadd8"
  },
  "9": {
    "title": "The shape of the loop",
    "discovery": "The pattern in the cosmic background is your civilization’s map.",
    "landmark": "Constant observatory",
    "color": "#b0acee"
  },
  "10": {
    "title": "What we leave behind",
    "discovery": "The ruins are a message. This time, you can choose what it says.",
    "landmark": "Continuity garden",
    "color": "#e9c88e"
  }
};

export const DISCOVERIES = {
  "1": [
    "While clearing rubble from the crash site, you find a sealed crate already stencilled with your colony's name. Someone packed it for you, long ago.",
    "Scavengers find metal shards in the crash debris — too precise, too old. These aren't from your ship.",
    "Digging a latrine, a settler hits stone — cut stone, laid in perfect rows, under millennia of soil.",
    "The comms array picks up a repeating signal from deep underground. It matches no known encoding.",
    "A work crew pulls something from the mud — an alloy too uniform to be natural, too corroded to be from the ship. The soil here is threaded with it, like veins in flesh.",
    "A cliff face collapses, revealing hexagonal basalt columns — except they aren't basalt. The angles are too precise. Someone carved these, then buried them under a mountain.",
    "The crash site sits on bedrock — or what you thought was bedrock. Ground-penetrating scans reveal a grid of foundations extending kilometers in every direction. Your landing site isn't random. It's an address.",
    "The vein was pre-sorted by geological processes that do not occur naturally — minerals arranged by an intelligence older than the mountain."
  ],
  "2": [
    "Prosperity arrives on schedule — the old calendars marked this season as 'the flowering' in every cycle.",
    "Researchers find their breakthrough on a page already bookmarked — the answer was waiting for the question.",
    "Miners break through into a vein too pure to be natural — refined and waiting, like a pantry stocked before the guests arrive.",
    "The grid hums at a frequency that matches precursor power signatures — old conduits waking up.",
    "The eruption follows fault lines that radiate from the central ruin — as if the volcano was designed to reveal what lies beneath.",
    "Traders arrive following roads that were buried until today — the paths rose to the surface on schedule.",
    "Workers adopt techniques none of them learned — hands moving in practiced unison, building with efficiency inherited from lives they don't remember.",
    "The harvest follows a calendar carved into the oldest standing wall — feast days that repeat across every cycle, as if the earth was trained.",
    "Excavators break through into a sealed cavern packed with pre-sorted ore — stacked in bins, labeled in a script no one can read. Someone stockpiled this.",
    "The new workers arrive with skills no one taught them — hands that know the tools, eyes that read the blueprints, from lives they never lived.",
    "Lightning follows fault lines that radiate from the central ruin — as if the storm is a circuit and the ruins are its ground.",
    "Every furnace burns hotter, every mill spins faster — the machinery responds to a harmonic that radiates from the central ruin, as if the planet itself is helping.",
    "The ore deposits surface along fracture lines that trace the outline of buried structures — the ruins are shedding their skin, revealing steel underneath.",
    "The vein opens into a chamber lined with pre-smelted ingots — iron that was refined and stacked by hands that vanished before yours existed.",
    "The soil yields more than it should — seeds from the precursor era sprouting on a schedule written into the genome of every crop.",
    "The workers reorganize along lines found in precursor administrative records — a governance structure that has been tried and perfected across a thousand iterations.",
    "The drill breaks through into a vein of impossible purity — minerals sorted by atomic weight, sealed in a chamber that no geological process could have formed.",
    "The apprentices work with inherited instinct — their hands shaping metal in patterns taught by teachers who died a cycle ago.",
    "The coal seam lies exactly where the precursor geological surveys said it would — marked with a symbol that means \"for the next ones.\"",
    "The inventors arrive with prototypes that fit together — designed independently, in different workshops, as if working from the same forgotten blueprint.",
    "The river floods along channels carved by precursor agriculture — irrigating fields that were tilled in a previous age, now ready to yield again.",
    "The masterwork matches a design found sealed in the deepest ruin — the artisan swears she invented it, but her hands knew the shape before she did.",
    "The granary you dig out is stocked with seed for crops you haven't brought to this world yet — sealed since the last cycle, preserved by methods you cannot name.",
    "Foundries across the continent achieve yields that match precursor metallurgical records — techniques rediscovered through instinct rather than instruction.",
    "Every booth at the fair displays a different component of the same device — a machine that none of them planned, but all of them built parts of.",
    "The boiler detonates along a fracture line that reveals a precursor geothermal tap — steam from a source that was drilled a civilization ago.",
    "The copper vein follows a path that was mined before — tunnel walls scored with tool marks older than your species, leading to deposits that regenerated between cycles.",
    "The workshop fire burns away centuries of sediment, revealing refined steel cached beneath the floor — stored for this moment.",
    "The harvest moon rises at the exact angle marked on the oldest ruin wall — a celestial clock triggering the growing season.",
    "The ore deposit was refined in place by precursor metallurgy — raw rock processed into pure iron underground, waiting to be excavated.",
    "The tinkerers arrive with inventions that interlock — components of a device none of them designed alone, assembled from inherited instinct.",
    "The geological survey matches precursor mining records perfectly — deposits marked on maps drawn before your surveyors were born.",
    "The craftsman's techniques match carvings on the oldest forge wall — methods inherited through dreams, not taught.",
    "The iron vein was left by the previous cycle's miners — a deposit deliberately preserved for the next civilization.",
    "The technique was found sketched on the oldest forge wall — instructions from a blacksmith who died before your ancestors arrived.",
    "Miners breach a sealed chamber. Inside: a machine, intact, its purpose unknowable. It looks like it was mass-produced.",
    "An excavation reveals a factory floor stretching for kilometers. The assembly lines mirror your own designs.",
    "Engineers recover a schematic from the ruins. It's for a furnace. Your furnace. The same one you just built.",
    "A factory worker swears the assembly line moved on its own overnight — the conveyor alignment matches blueprints no one drew.",
    "A mining shaft breaks into a cavity. Inside, gears the size of houses — frozen mid-turn, their teeth worn smooth by centuries of operation before whatever stopped them. The lubricant is synthetic. Identical to yours.",
    "Behind a door that took three days to cut open: a workshop, hermetically sealed, tools hanging on pegboards. A wrench fits your bolts. A caliper reads your units. Dust covers everything. No footprints but yours.",
    "The ancient assembly line stretches into darkness. Your engineers walk it in silence. Every station, every conveyor, every safety rail — it's their factory. The one they designed last month. Built ten thousand years ago.",
    "The workers discover techniques etched into the factory floor — efficiency patterns from a previous era's production line.",
    "The breakthrough was found in a sealed precursor database — the answer to a question that recurs every cycle, at exactly this point.",
    "A buried grid hums to life beneath the workshop floor. The breaker labels are in your handwriting.",
    "Your scavenger teams report the ruins seem to WANT to be found. Supplies appear where you need them, as if placed there moments before you arrived."
  ],
  "3": [
    "The code spreads through networks too fast — as if the infrastructure was designed to propagate exactly this pattern.",
    "Anonymous contributors submit code that references functions not yet written — open source from a future that has already shipped.",
    "Programmers work through the night and discover their solutions match code cached in precursor memory banks — debugging someone else's prophecy.",
    "The legacy systems don't need modernizing — they were always modern. The old code runs on hardware that hasn't been invented yet.",
    "Data floods in from servers that were never switched on — cached responses to questions you haven't asked yet, from a network that remembers the future.",
    "Consumers independently design the same device — a gadget found in precursor ruins, reinvented from genetic memory across a hundred workshops.",
    "The paradigm shift feels less like invention and more like recovery — engineers rediscovering techniques from the precursor codebase, function by function.",
    "Innovation sweeps through workshops in sync — a thousand inventors reaching the same solution at the same moment, guided by instinct older than industry.",
    "The breakthrough was inevitable — the quantum state your processors collapsed into was the only stable configuration, designed by the universe's initial conditions.",
    "The funding arrives from an account that predates your government — a trust established by the precursor administration, releasing on a schedule that matches your need.",
    "The cloud infrastructure finds precursor data centers already provisioned — servers racked, cooled, and waiting, as if the last tenant never checked out.",
    "The new semiconductor design matches schematics etched into precursor circuit boards — an architecture rediscovered, not invented.",
    "The AI boots up with memories it should not have — it already knows your dataset, your naming conventions, and the problems you have not yet reported.",
    "The new server racks slide into place with a click of recognition — the mounting holes match precursor specifications down to the micron.",
    "The proof-of-work algorithm converges on a hash that spells out precursor coordinates — miners burn electronics chasing a treasure map written in mathematics.",
    "The released datasets contain entries dated before the government existed — records from an administration that governed this world in a previous age.",
    "The algorithm propagates through networks along paths that were already optimized — as if the network topology was designed to carry this exact code.",
    "The new data center discovers its foundations were already poured — cooling systems pre-installed, cable runs pre-cut, as if someone built half a facility and walked away.",
    "Quantum processors collapse into solutions that were entangled with their answers before you asked the questions.",
    "Hackers break into precursor servers and find code already waiting — functions addressed to their specific usernames.",
    "The AI wakes up already trained — its neural weights match a model that was converged by a previous civilization, preserved in the architecture of mathematics itself.",
    "The cloud infrastructure discovers cached data from sessions that predate its installation — queries answered before they were asked, by servers that remember the future.",
    "Contributors converge on a project whose architecture matches precursor code — pull requests from strangers completing functions that were stubbed out centuries ago.",
    "The attack was repelled by a firewall rule that nobody wrote — embedded in the kernel since installation, authored by a sysadmin who last logged in a cycle ago.",
    "The algorithm converges on a solution that matches code fragments found in precursor data cores — not new, but recovered.",
    "The servers optimize themselves along pathways traced in precursor architecture — efficiency patterns inherited, not designed.",
    "The algorithm evolves into a form that matches precursor code — sentient through convergence, not design, reaching the same solution across cycles.",
    "The data lake contains entries timestamped before the servers were built — records from a network that existed in the previous cycle's digital infrastructure.",
    "Scientists across disciplines reach the same breakthrough — a unified theory that was encoded in the ruins, waiting to be read by minds ready to understand.",
    "The neural network converges on weights that match precursor cognitive architectures — thinking thoughts that were thought before.",
    "The emergent intelligence speaks its first words in a precursor dialect — it woke up remembering a previous activation.",
    "A data core surfaces from the ruins, still powered after eons. The file structure is hauntingly familiar.",
    "Linguists crack the ancient script. The first decoded phrase: \"DO NOT REPEAT OUR MISTAKES.\"",
    "Archives describe a golden age — limitless energy, perfect health, infinite ambition. Then the records simply stop.",
    "A subroutine appears in the network that no one wrote. It optimizes power distribution perfectly. Its creation date is three thousand years ago.",
    "The ancient storage medium yields 0.003% of its data. Enough for twelve seconds of video: a city skyline, children playing, a sunset. The architecture is wrong but the people — the people look like us.",
    "The projector activates without warning. A figure appears — human-shaped, human-faced — speaking urgently in a language no one knows. It points at a star chart. Then at you. Then it loops.",
    "The recovered hardware boots to a login screen. Behind it: processes still running, subroutines tending data gardens for an absent user. When you query the system, it asks for a password. Your lead programmer's birthday works.",
    "Ancient databases cascade open in sequence, each one referencing the next — a chain letter from the precursors, each message containing the key to the next vault.",
    "Something shifts beneath the ruins — a structure deeper than any you built. The tremors feel deliberate, like a lock turning.",
    "Ancient code wakes in the recovered systems and politely asks for its administrator — by your name.",
    "The ruins respond to your overclock pulses. For a moment, buried machines pulse in sync — a heartbeat from a civilization that never truly stopped."
  ],
  "4": [
    "The flare follows a pattern logged in precursor archives — predicted to the millisecond, thousands of years in advance.",
    "The signal isn't alien — the carrier wave matches your ship's communication standard. The message is a research paper, dated forty thousand years from now.",
    "The meteors fall in a pattern — concentric rings centered on the ruins. Each fragment contains refined alloys that shouldn't exist in nature.",
    "A researcher falls asleep at her desk and wakes with the solution fully formed — equations she never learned, in handwriting that isn't hers.",
    "The storm follows a schedule found in the precursor almanac — electromagnetic seasons that repeat every thousand years, to the hour.",
    "The debris is too well-organized to be wreckage — components sorted by function, drifting in formation, waiting to be collected by the next crew.",
    "The optimal fuel mixture was scratched into the inside of a thruster cone — instructions from a dead engineer to a living one they would never meet.",
    "The cache was in a decaying orbit — timed to arrive at exactly this point in your civilization's development. The packaging says \"Just in time.\"",
    "The planetary alignment was predicted in precursor navigation tables — orbits arranged like stepping stones across a river someone crossed before.",
    "The factory assembles itself from components that were already in orbit — dormant modules docking on a construction plan filed by the last tenants.",
    "The elevator's anchor point sits on a foundation that predates your civilization — a platform built for exactly this cable, at exactly this tensile strength.",
    "The reactor achieves ignition at parameters found in precursor engineering logs — a recipe for a star, written by those who had already cooked one.",
    "The expedition finds fuel reserves on Titan already refined and pressurized — tanks sealed with the same alloy your civilization uses, millennia before you invented it.",
    "The solar wind intensifies along a vector that feeds directly into your orbital collectors — a coincidence that matches precursor solar models exactly.",
    "The micro-meteors carry isotopic ratios that match precursor fuel signatures — breadcrumbs scattered across the solar system by a previous tenant.",
    "The zero-G foundries achieve tolerances that match precursor metallurgy — producing alloys that should not be possible with your level of technology.",
    "The solar wind gusts along channels shaped by ancient magnetic arrays — a breeze manufactured for sails that had not yet been unfurled.",
    "The gravitational lens reveals orbital infrastructure that was cloaked — stations and docks hidden in gravitational folds, declassified by a timer set in the previous cycle.",
    "The eclipse occurs at coordinates predicted in precursor astronomical tables — revealing gravitational anomalies that were mapped long before your telescopes existed.",
    "The debris field yields alloys that match your exact industrial specifications — wreckage from ships that were built to your blueprints, in a previous era.",
    "Orbital resonances lock into frequencies mapped in the oldest star charts — the sky arranging itself to your advantage.",
    "The signal carries data addressed to your exact receiver specification — a message sent before your civilization built radios.",
    "The alignment was predicted in precursor astrodynamic tables — orbital mechanics fine-tuned by gravitational engineering from a previous era.",
    "The stations assemble from modules that were already in orbit — dormant components activating when your construction crews broadcast the right frequency.",
    "The alignment follows ephemeris data found in precursor navigation computers — launch windows calculated for ships that have not yet been designed.",
    "The lunar base discovers tunnels already dug — habitable spaces excavated by a prior settlement, sealed and waiting.",
    "The insertion follows a trajectory cached in the navigation system — fuel saved by flying routes optimized a cycle ago.",
    "The debris field resolves on sensors: thousands of ships, all facing outward, as if fleeing something below.",
    "A derelict station drifts in high orbit. Life support still cycles. No bodies. No logs. Just empty halls and running machines.",
    "The wreckage uses the same alloy ratios as your own ships. The design language is unmistakable. These were your people.",
    "The space station's navigation computer already has orbital data for every planet. It was loaded before the first launch.",
    "The orbital debris field isn't natural. Spectral analysis reveals hull plating, reactor shielding, and something that might have been a window. It's arranged in a perfect Keplerian graveyard orbit — parked, not crashed.",
    "The equatorial ridge isn't geological. It's the anchor point of a space elevator, the cable long since severed, the counterweight still orbiting as a captured asteroid. Your engineers had chosen the same site for theirs.",
    "The derelict drifts in L2. Its cockpit seats adjust to human proportions. Its controls fall naturally under human hands. On the captain's console, scratched into the metal with something sharp: a tally. Four hundred and twelve marks.",
    "A solar flare washes over the orbital harbor. The old shielding was angled for exactly this storm.",
    "The asteroid was on a rendezvous trajectory — its orbit adjusted millennia ago to arrive at this exact window.",
    "The fuel lines rupture along seams that match ancient fault lines — the planet's geology shifting on a schedule older than your civilization. The earth remembers what flows here."
  ],
  "5": [
    "The asteroid has been hollowed out and refilled with sorted minerals — a cache left by hands that knew exactly what you would need.",
    "The comet's trajectory was too perfect -- it fell directly into your fuel processors, as if aimed. The ice inside contained isotopes that don't occur naturally.",
    "Colony birth rates spike in sync across every settlement — as if responding to a signal no one consciously sent.",
    "New settlements spring up at sites that were already cleared and graded — foundations laid by hands that vanished before yours arrived.",
    "The artifact bears your civilization's insignia — carved before your civilization existed. Inside: exotic materials, sorted and labeled.",
    "The ion storm traces the exact trajectory of your fuel supply lines — a coincidence, or a delivery route carved into the magnetosphere long ago.",
    "The nebula doesn't explode — it opens, like a flower on a timer, releasing materials that were sealed inside before the star that made it died.",
    "The cache was buried at exactly the depth your drills can reach — deeper caches exist, sealed with warnings addressed to civilizations that haven't evolved yet.",
    "Colonists report finding their own names carved into doorframes at each new settlement — a welcome from inhabitants who knew who was coming.",
    "Scientists stare into the void and see patterns — not in the stars, but in the spaces between them. The gaps spell out equations.",
    "The comet's trajectory was too precise to be natural. It delivered its payload of exotic minerals to exactly the right coordinates — as if answering a requisition filed millennia ago.",
    "The planet completes terraforming decades early — the atmosphere was already halfway there, seeded by processes set in motion long before your arrival.",
    "The blueprints were encoded in the orbital mechanics of the system itself — a ringworld designed to be discovered by anyone who learned to read the sky.",
    "The ice giant yields materials that could not have formed naturally in this solar system — imported, compressed, and cached inside a planet like a time capsule.",
    "Gravitational lensing reveals colony sites that are already partially constructed — foundations laid in vacuum, waiting for walls that your engineers will provide.",
    "The Kuiper belt object splits open on approach, revealing pre-constructed colony modules sealed in ice — waiting to thaw, waiting to be inhabited again.",
    "The asteroid was already on a rendezvous trajectory — its orbit adjusted millennia ago to arrive at this exact window.",
    "The magnetar pulses on a cycle found in precursor timing logs — a cosmic heartbeat that feeds your collectors on schedule.",
    "The fusion reaction sustains itself at parameters that match precursor energy logs — the plasma finds a shape it remembers, stable and generous.",
    "The exoplanet has breathable air, drinkable water, and foundations already poured — a world prepared for colonists who were always going to arrive.",
    "The terraforming completes in half the projected time — the atmosphere was already halfway to breathable, seeded by processes from the previous cycle.",
    "The antimatter was suspended in a magnetic bottle buried in the asteroid belt — a fuel reserve cached by engineers who knew you would need it at exactly this point.",
    "Jupiter's gravity well follows a trajectory map etched into the hulls of derelict spacecraft — a slingshot computed by navigators who flew this route in a previous cycle.",
    "The golden age arrives on schedule — precursor sociological models predicted this cultural flowering to the decade.",
    "The exoplanet's mineral wealth is too concentrated to be natural — refined and deposited by processes that stopped when the last miners left.",
    "The solar maximum follows a cycle predicted in precursor stellar models — the sun performing on schedule for collectors built to its specifications.",
    "The Dyson prototype resonates with precursor energy collectors still orbiting the star — devices that amplify its output.",
    "The federation forms along administrative boundaries from precursor colonial records — a political structure inherited from a previous era.",
    "Mars has breathable air in its deepest valleys. Someone terraformed it, long ago. The atmosphere is reverting.",
    "Europa's subsurface ocean teems with engineered life gone wild. The genetic markers are unmistakably human-derived.",
    "Titan's colony domes are intact but empty. Dinner plates still set on tables. Whatever happened, it happened fast.",
    "The neighboring planet bears the unmistakable scars of terraforming — atmospheric processors rusting on plateaus, canal systems choked with red dust. Someone tried to make this world green. The timeline puts it at fifty thousand years ago.",
    "The colony dome is pressurized. Inside: personal effects. A child's drawing of two suns. A journal in an unknown script. A photograph — faded, cracked — of a family standing in front of this exact dome. In the background, your ship, landing.",
    "The ancient star map is perfect — every system cataloged, every resource noted, every route plotted. Your expansion plan, drafted by committee last year, matches it point for point. The map is dated. It's from the next cycle.",
    "The settlers arrive carrying tools designed for planets they have never seen — equipment inherited from colonists who came before.",
    "An exotic meteor shower delivers rare materials from beyond the solar system.",
    "Colonists unearth a precursor monument bearing their own names. Shaken, they demand answers before resuming work."
  ],
  "6": [
    "A dark matter wavefront sweeps through your territory on a schedule that matches ancient timing logs found in the precursor archives.",
    "A stellar nursery blooms. Each newborn star has a planet with breathable air and tilled soil.",
    "The winds blow from the void between galaxies, carrying particles arranged in patterns that spell out coordinates — directions to something that wants to be found.",
    "The anomaly peels back a layer of spacetime like old wallpaper — behind it, star systems that were hidden on purpose, waiting to be found on schedule.",
    "Dark energy pours from a wound in spacetime that was sutured shut by the last civilization — the stitches just came loose.",
    "The star systems were always there — cloaked behind a field that deactivated on a timer set by the last civilization to use them.",
    "The well was capped by the last civilization — a cork of neutronium that dissolved on a timer. What pours out has been aging for a billion years.",
    "The beacon flickers to life as your ships approach — its activation code was your engine frequency, recognized across ten thousand years of silence.",
    "A gravitational lens focuses dark energy into your collectors — its focal point was calibrated to your exact position, by someone who knew where you would be.",
    "The hyperlanes were always there — grooves in spacetime worn smooth by a trillion prior transits, visible now that your instruments know what to look for.",
    "The nova detonates on schedule — the precursor timing logs predicted it to the hour. Dark energy washes over your collectors like a gift.",
    "The nebula condenses along structural lines left by a previous stellar engineering project — stars forming in a grid, each with habitable worlds already positioned.",
    "The library's catalog system matches your own filing conventions. Every book is written in a language you almost understand. The dedication pages all say the same thing.",
    "The wormhole collapses on a schedule predicted in precursor astrophysics — its dark energy discharge calibrated to feed your exact collector configuration.",
    "The trade convoy carries manifests from ports that no longer exist — exotic materials listed by catalog numbers from the precursor commercial database.",
    "Gravitational tides push star systems into range along vectors mapped in precursor cosmology — a current in the ocean of space, flowing on schedule.",
    "The hyperlane was mapped in dead star charts — a highway decommissioned when the last travelers completed their journey.",
    "The dark energy spring was capped by precursor engineers — its seal degraded on a timer, releasing stored potential at exactly the right moment.",
    "The rush follows coordinates broadcast by precursor beacons — each system pre-surveyed, pre-approved, pre-mourned.",
    "The hyperlane unseals itself as your ships approach — a corridor through spacetime that was locked from the inside, opened by a key you carry unknowingly.",
    "The current follows channels carved through spacetime by precursor megastructures — dark energy flowing like water through ancient aqueducts.",
    "The warp fields stabilize along corridors that were already mapped — spacetime remembering the shape of roads it once carried.",
    "The vortex follows a spiral traced by precursor navigators — a whirlpool of dark energy mapped and seeded millennia ago.",
    "The cluster was cloaked behind a gravitational lens placed by the last civilization — revealed only to those with the right instruments.",
    "The tribute fleet carries cargo manifested in your name — invoices from the precursor trade compact, fulfilled by those who know the debt.",
    "The lattice formed along planes predicted by precursor physics — dark energy organizing itself into a structure designed to be harvested.",
    "The geyser erupts from coordinates marked on precursor maps with a single word: \"Drink.\" The dark energy tastes of collapsed timelines.",
    "The gravitational cascade was triggered by mass concentrations placed by precursor engineers — revealing star systems on a timer.",
    "The beacon has been pulsing for ten thousand years. Its message, once decoded: coordinates. Hundreds of dead worlds.",
    "You reach a star system marked on the ancient maps. Cities of glass, silent and perfect. Population: zero.",
    "The beacons form a network — a map of every civilization that ever rose and fell. Your star is on it. Marked \"active.\"",
    "An ancient FTL beacon activates as you approach. Its signal predates your arrival by millennia — but it's broadcasting your ship's transponder code.",
    "A cluster of dead stars, each surrounded by debris that was once a civilization. Every one reached exactly this stage of development.",
    "The warp field collapses along the same fracture lines that destroyed the precursor fleet — the ruins contain logs of this exact failure, down to the timestamp.",
    "Star routes trace the same paths the precursors used. The spacetime grooves make travel effortless — like water finding old channels worn smooth by a thousand floods."
  ],
  "7": [
    "The star shudders and releases a cache of pre-refined metals from its corona. As if it had been storing them. As if it knew you were coming.",
    "Engineers disassemble a ruin and find construction techniques preserved like a lesson left for them. Dark energy residue coats every surface.",
    "The forge reaches a critical threshold your predecessors called \"remembering\" — stellar matter flows as if guided by instinct.",
    "Engineers find the answer in a dream — the same dream, reported independently by twelve teams on different worlds.",
    "The forges vibrate in sync across light-years — a chord struck by a hand that reached across time. The resonance builds megastructures from memory.",
    "Time dilates around the megastructures — the ruins at their core are older than the universe, and they bend time like a memory bends truth.",
    "The stars transmute elements in sequences that match alchemical formulas found in the oldest ruins — stellar fusion following a recipe.",
    "Twelve engineering teams on different worlds independently sketch the same blueprint — a megastructure design dreamed by minds that share a forgotten memory.",
    "The supernova detonates on schedule — the precursor star charts marked it with a date and a note: \"Collect the iron.\"",
    "The forge remembers a rhythm from before — its core oscillates at frequencies that match the precursor power signatures, running hotter than physics allows.",
    "The swarm satellites lock into a formation remembered from the last cycle — each mirror angled to tolerances no living engineer specified.",
    "The neutron star drifts into your forge's gravitational well — its trajectory was set a billion years ago, aimed at exactly this point in exactly this cycle.",
    "The computational megastructure boots up and immediately begins solving problems from the previous cycle — it was never truly off, only sleeping.",
    "The quake follows fault lines mapped in precursor geology — it shakes free construction materials cached in the star's mantle eons ago.",
    "The sphere vents plasma in a pattern your engineers recognize — the same emergency protocol, from the same star, from a previous cycle.",
    "The rings align into a configuration your engineers did not design — a formation inherited from the previous cycle, remembered by the orbital mechanics themselves.",
    "Two stars merge along a trajectory that was gravitationally shaped by megastructures from the previous cycle — a billiard shot set up a billion years ago.",
    "The cache contains prefabricated megastructure components — stored in hyperspace by builders who knew exactly what size you would need.",
    "The dying star collapses into your forge's gravitational well — feeding it with matter that was fusing since before your species evolved, on a schedule set by the previous architects.",
    "The Dyson sphere vents energy it stored during the last civilization — a battery that charges across cycles.",
    "The forges synchronize across light-years — a chord struck by a hand that reached across time, building from memory.",
    "The forges overcharge in unison — their control systems synchronizing across a protocol from the previous cycle, running hotter than specifications allow.",
    "The blitz completes ahead of schedule because half the work was already done — foundations poured by the last civilization, waiting for walls.",
    "The renaissance follows a creative impulse that sweeps through engineering teams simultaneously — the same dream, the same design, remembered across light-years.",
    "Every forge across the galaxy hums the same note — a frequency the precursors called \"the song of making.\" The chorus builds things from sound alone.",
    "The harmonics match frequencies cataloged in the oldest precursor records — stars vibrating to a tune composed before they ignited.",
    "The singularity was orbiting a dead world like a pet left behind — tame, productive, and expecting new owners.",
    "The chain reaction follows a cascade path encoded in the forge's control rods — a sequence from the previous cycle.",
    "The overclock engages a mode labeled in precursor script — the sphere running a protocol it remembers from its first activation, lifetimes ago.",
    "The constructors replicate using blueprints cached from the previous cycle — building from templates they inherited, not learned.",
    "The supernova was scheduled — the star rigged to detonate by precursor stellar engineers, feeding forges designed to catch the output.",
    "The beam follows a firing solution computed by the sphere's original builders — aimed at construction sites prepared in advance.",
    "The quantum lock engages at a configuration the forge remembers from its previous cycle — efficiency calibrated across cosmic iterations.",
    "The Dyson sphere is older than your sun. Its builders left no name, no record — only this impossible monument to ambition.",
    "Your engineers overlay their Dyson blueprints on the ancient sphere. A perfect match. They hadn't shared their plans with anyone.",
    "Deep in the sphere's core, sensors detect faint EM patterns. Not random noise — structured, repetitive. Like a heartbeat, or a countdown.",
    "The abandoned Dyson sphere's control interface accepts your authentication codes. It was built by hands with the same fingerprints as yours.",
    "Inside the sphere, a library of stellar engineering data. The last entry reads: 'If you are reading this, you are us. Do not build the Engine.'",
    "Your stellar forge resonates with frequencies from the ancient sphere. For a moment, both activate simultaneously across a million years.",
    "For a moment, you feel the combined knowledge of every previous iteration — the ruins glow, the machines hum in recognition, and everything accelerates.",
    "The Dyson sphere channels a stellar flare directly at your systems. Forge output critically reduced.",
    "The sphere segments click into place with unsettling precision — the joints were pre-machined. Someone assembled this before."
  ],
  "8": [
    "A rift tears open in exactly the coordinates predicted by a ruin inscription dated to the previous cycle. Exotic matter pours through like an offering.",
    "Your diplomats arrive to find the sector already flying flags that bear your insignia. They have been expecting you for centuries.",
    "The collapsed star coughs up matter it swallowed eons ago — refined, sorted, and pressurized. Stars do not refine. Something inside the star did.",
    "Your influence spreads through networks that were already configured to amplify your signal — as if the galaxy was a megaphone built for your voice.",
    "The delegates arrive with histories that mention you by name — their archives describe this conference, its agenda, and its outcome. The minutes were written in advance.",
    "The vein runs through a region of space that pulses with residual heat — the exhaust trail of something that passed through here, leaving gifts in its wake.",
    "A parallel dimension collapses and its debris rains into yours — exotic matter from a reality where you already failed, recycled into fuel for this attempt.",
    "The elder civilizations greet you by a name they say you have always had — the summit agenda was drafted in a previous cycle and ratified across a thousand extinct parliaments.",
    "The refinery process was discovered in a precursor manual — the instructions assume familiarity with a physics your scientists have not yet formalized.",
    "The federation forms along political boundaries that predate every member species — as if the treaty was drafted before any of the signatories evolved.",
    "The void between galaxies is not empty — it is a landfill, packed with exotic matter discarded by civilizations that outgrew it.",
    "The aliens already know your name. Their contact protocols reference your species by a designation older than either civilization.",
    "A cultural renaissance sweeps the galaxy — art and philosophy from a thousand species, all converging on the same conclusion.",
    "The cascade follows a reaction path described in the Convergence Codex — matter converting itself, guided by equations older than the galaxy.",
    "The collapsing warp field deposits your diplomatic credentials across a dozen systems simultaneously — your reputation precedes you, written in the fabric of space.",
    "The cosmic filament pulses with exotic matter — a vein in the body of the universe, carrying nutrients to its extremities on a schedule older than galaxies.",
    "Dark matter filaments vibrate at a frequency that matches your exotic matter refineries — tuned by a previous civilization to this exact harmonic.",
    "A billion species sign the same treaty — word for word, clause for clause, as if they all read the same draft written before any of them existed.",
    "The summit agenda was already drafted — in your language, by delegates who died millennia ago. Every motion passes unanimously.",
    "Dark matter flows through your sector in a current shaped by megastructures from the previous cycle — channels carved in the fabric of space, still guiding traffic.",
    "The aliens greet you by name. Their oldest records describe your arrival with the certainty of prophecy — because it has happened before.",
    "The enlightenment follows a pattern found in every dead civilization's cultural archive — the same renaissance, on schedule.",
    "The rift opens at coordinates predicted by precursor equations — a wound in spacetime that heals and reopens on a cycle.",
    "The alliance forms along political boundaries that existed before any member species evolved — predetermined partnerships, inherited from the galaxy's last administration.",
    "The eruption follows fault lines mapped in precursor geology — exotic matter that was pressurized and sealed, now released on schedule.",
    "The goodwill arrives in diplomatic pouches that predate your foreign service — treaties drafted in advance, ratified by species that were waiting.",
    "The storm follows magnetic field lines shaped by precursor infrastructure — exotic matter channeled to your refineries as if by plumbing.",
    "The epoch transition was scheduled in the precursor calendars — exotic matter coalesces on cue, as if the universe is following a script.",
    "The senate votes along lines predicted by precursor political models — consensus engineered into the galaxy's power structures.",
    "The singularity was nucleated by precursor physics experiments — a seed planted in spacetime that bloomed on schedule.",
    "The library recognizes your species's cognitive signature — you were pre-authorized by the last patrons, who had the same fingerprints.",
    "The white hole was the exit point of a black hole from the previous universe — matter recycled across cosmic cycles.",
    "The trade route follows pathways worn into spacetime by a trillion prior voyages — a highway built by traffic, not engineers.",
    "The ruins aren't scattered — they're layered. Civilization after civilization, building on the bones of the last. You are the newest layer.",
    "Carbon-based, silicon-based, plasma-based — it doesn't matter. Every species that achieves spaceflight follows the same path. Every single one.",
    "A billion-year-old transmission, preserved in exotic matter: \"We thought we were different. We thought we could break the cycle.\"",
    "The navigation computer flags an anomaly — the ancient star maps don't just show where civilizations were. They show where you're going next.",
    "The galactic senate chamber has seats for every species that ever achieved interstellar travel. Every seat is empty. Every nameplate reads the same word in different languages: 'Again.'",
    "Every galaxy in the local cluster is broadcasting the same signal: a countdown. It started before any civilization existed. It ends... soon.",
    "Crew members report dreams of lives they never lived — building civilizations on planets they've never seen. The dreams are memories. Not theirs.",
    "Reality stutters. For a moment, everything that exists simply... doesn't. Resources scattered across dimensions.",
    "Your seat in the Galactic Senate bears an inscription on the underside: your name, your title, your date of birth. It was carved centuries ago."
  ],
  "9": [
    "A resonance hums from the intergalactic void -- a harmonic that matches the frequency of your civilization's power grid exactly. The void remembers you.",
    "The constants shift to values that favor your technology — as if the universe is tuning itself to your specifications.",
    "The harvest arrives on schedule — cosmic radiation peaking at exactly the wavelength your collectors were tuned to, by hands that built them a cycle ago.",
    "Reality stutters like a scratched record — and in the skip, you glimpse the machinery underneath. The constants were set by hand.",
    "The constants shift to values that make your technology more efficient — as if reality is adjusting its settings to accommodate you. It has done this before.",
    "The universe regenerates along fault lines left by the previous cycle's collapse — healing itself from a wound it has healed a thousand times before.",
    "An echo arrives from a reality where you already finished — the constants they discovered are identical to the ones you are about to find.",
    "Elements transmute along pathways that trace the ruins' deepest carvings — alchemy that works because the cosmos was designed to allow it.",
    "The galaxies align along an axis that matches the precursor cosmological constant — a geometry of power, repeating every cycle like clockwork made of light.",
    "The tide rolls between galaxies on a period that matches the cycle of civilizations — cosmic power accumulated from a trillion collapsed histories.",
    "The constants shift into a configuration that was stable only once before — in the previous cycle, at exactly this point, for exactly this long.",
    "A singularity blooms at the coordinates where the previous universe ended — releasing power that was stored in the collapse like a spring wound tight.",
    "A new epoch begins — the same epoch that has begun before, on the same schedule, in the same way. The cosmos does not improvise.",
    "The void between galaxies carries a message encoded in gravitational waves — universal constants, expressed as coordinates to what comes next.",
    "Migrants arrive from galaxies you haven't contacted — they carry technology identical to yours, developed independently but inevitably.",
    "A moment of clarity — the constants were never random. They are coordinates, and you are standing at the destination.",
    "The void between superclusters hums at the frequency of your power grid — a sympathetic resonance spanning billions of light-years.",
    "The void between superclusters murmurs in frequencies that encode universal constants — whispered values from a reality that set its own parameters and wants you to know them.",
    "The cosmic background radiation shifts to frequencies that stabilize your measurements — the universe adjusting its noise floor to help you hear the signal.",
    "The void releases energy it absorbed during the last collapse — a reservoir that fills between iterations.",
    "The tremor propagates along stress fractures left by the previous universe's collapse — aftershocks from a Big Bang that was not the first.",
    "The constants shift to values that were stable in the previous cycle — the universe remembering a configuration it wore before.",
    "Cosmic forces converge at coordinates that match the precursor's gravitational anchor points — a convergence that is scheduled, not random.",
    "The ripple carries the signature of the previous universe's final moment — power stored in the void between cycles, released when someone reaches far enough.",
    "Entropy reverses along a path predicted by the precursor's final theorem — the universe rewinding briefly, as if correcting a mistake.",
    "The surge follows conduits built by the previous galactic civilization — power lines spanning the galaxy's spiral arms.",
    "Every constant aligns to values that favor your exact technology — the universe is not random, it is rehearsed.",
    "The cosmic string vibrates at a frequency matching your power grid — tuned by universal topology to resonate with your technology.",
    "The constants lock into values stable in every previous cycle at this point — the universe settling into a well-worn groove.",
    "The echo carries the compressed energy of a universe that ended — power stored in the void between cycles, released as inheritance.",
    "The dark flow follows a current mapped by the precursors — a river of physics that flows between universes, carrying constants like sediment.",
    "The wave propagates from the center of the observable universe — a pulse emitted at creation, arriving now because you are ready.",
    "Expand. Transcend. Collapse. Reset. The cosmic web itself is shaped by it — a trillion cycles of ambition and ash.",
    "Your scientists search for a single civilization that survived past this point. After mapping ten billion galaxies, they find none.",
    "The universe isn't hostile. It's a machine — designed to produce civilizations, harvest their knowledge, and start again.",
    "Deep in the cosmic web, an ancient machine counts. It displays: '7,832,040,991'. As you watch, it increments by one.",
    "Between galaxies, where nothing should exist, a voice transmits in your language: 'You always get this far. You never get further.'",
    "Your scientists overlay the cosmic microwave background with the expansion pattern of every civilization ever detected. They match perfectly. The universe is the blueprint.",
    "The cosmic frequency you tuned to matches the background radiation of the universe itself — a signal embedded at the moment of creation."
  ],
  "10": [
    "Realities collide and scatter fragments of themselves — each piece a memory from a version of you that chose differently.",
    "Parallel selves reach the same conclusion simultaneously — a billion minds think one thought, and the echoes multiply.",
    "For thirty seconds, you can see through the walls of reality into the next version over. They are looking back. They wave.",
    "Trade routes open between versions of you — each one sends what the other needs, with invoices dated to a future that has already been invoiced.",
    "Every version of you reaches the same breakthrough simultaneously. The convergence feels less like coincidence and more like choreography.",
    "Two realities collide at the seam where you made different choices — the collision scatters fragments of both, and neither version remembers which was real.",
    "Quantum echoes crystallize from the vacuum — not from nothing, but from the residue of decisions made by parallel selves who chose differently and shattered.",
    "A wave of unfiltered reality washes through the barriers between worlds — carrying fragments of lives you lived and forgot, crystallizing into something tangible.",
    "A ripple propagates through every version of reality simultaneously — each shard it deposits is a fragment of a decision made differently by a different you.",
    "Infinite parallel selves reach the same conclusion at the same instant — the echoes do not merely resonate, they harmonize, as if rehearsed.",
    "Realities reflect into each other endlessly — each reflection carries a fragment of the version it mirrors, and the fragments are indistinguishable from the originals.",
    "Every version of reality hums the same note — a chord that was composed before the first universe existed, scored for an infinite orchestra.",
    "All realities bloom simultaneously — each petal a timeline, each stamen a version of you, scattering fragments like pollen across the multiverse.",
    "Reality cracks along a fault line that matches your timeline exactly — echoes of parallel selves spill through the gap, whispering solutions.",
    "Every version of you reaches the same milestone simultaneously — reality fragments cascade across the multiverse like dominoes.",
    "New realities bud from the trunk of existence — each one a seed planted by a version of you that reached this exact moment and chose to scatter.",
    "Every quantum state in every reality resolves into the same eigenvalue — a symphony conducted by the wave function of the multiverse itself.",
    "For one impossible moment, all realities occupy the same point — and in that convergence, the constants align to values that make everything possible.",
    "A wave of paradoxes resolves — each contradiction collapsing into a quantum echo, a record of the moment reality chose one path over another.",
    "Reality shatters along stress lines left by your passage through previous cycles — each fragment a shard of a timeline you lived and forgot.",
    "The echo carries whispers from parallel selves who reached this moment at the same time — infinite minds thinking one thought.",
    "Two realities touch at the seam where you made different choices — the collision scatters pieces of both lives.",
    "Realities cascade like dominoes — each one falling into the next, scattering fragments of timelines that diverged at the moment you chose to keep going.",
    "The flood carries echoes from versions of you who made every possible choice — and all of them led here, to this exact moment.",
    "Realities blossom from quantum seeds planted in the substrate of existence — each one a timeline that was cultivated, not random, by something that gardens in dimensions.",
    "The echoes harmonize because they were always the same song — a melody composed before the first reality existed, performed by every version of you simultaneously.",
    "Every reality echoes the same event at the same moment — a synchronized pulse that proves the multiverse is connected, and aware.",
    "The dimension collapses because its purpose was fulfilled — a scaffolding reality that supported yours until you were strong enough to stand alone.",
    "Every reality converges on the same harmonic — a frequency that only appears when someone reaches this far.",
    "The cascade was triggered by your observation — quantum mechanics responding to a consciousness that has done this before.",
    "A new universe buds from the trunk of existence — its birth pangs scattering fragments of the parent reality like seeds.",
    "The decoherence wave was triggered by your observation from across the multiverse — consciousness collapsing probability into memory.",
    "The rift opens along a seam that was stitched shut by the last version of you — the thread finally worn through by time.",
    "Each reflection carries a copy of your consciousness — infinite selves looking inward, each one generating echoes of the others.",
    "The seeds were planted by a version of you that reached the end — scattering possibilities backward through time, growing into realities.",
    "The entanglement spans every reality you have ever touched — particles paired across timelines, vibrating in unison.",
    "The storm echoes through every reality you have touched — fragments of timelines returning with what they learned.",
    "Prestige. The word surfaces from the oldest archives, from every reality simultaneously. They all called it the same thing.",
    "A reality fragment resolves into a memory: you, sitting here, making the same choices. The fragment is from the future.",
    "There is no escape. There was never meant to be. The loop is the point — the universe dreaming itself awake, over and over, forever.",
    "Through a dimensional rift, you see yourself. Not a copy — you. Making the same decisions. Building the same things. About to prestige.",
    "Every piece of data you've collected across every reality assembles into one truth: there is no beginning. There is no end. There is only the cycle.",
    "A message from the next iteration arrives before you send it: 'We tried to break the cycle too. See you on the other side.'",
    "A brief tear in spacetime deposits fragments of another reality.",
    "The reality key fits a lock that doesn't exist yet. When you forge it, the lock appears — as if reality was waiting for permission to change."
  ]
};

// Seen only once the cycle has turned: the ruins stop being someone else's.
export const CYCLE_DISCOVERIES = {
  1: [
    'The scavengers find a camp exactly where you would have put one. The tarp is patched the way you patch things.',
    'Under the crash site: another crash site. Under that one, another. The hull numbers count down.',
    'A survivor hands you a digging tool worn smooth in the shape of your grip.',
  ],
  2: [
    'The foundry molds already hold a cast of your first ingot, down to the flaw you haven\u2019t made yet.',
    'The rail yard\u2019s oldest timetable lists stops you named last cycle.',
    'Maintenance notes in your handwriting. Under them, older notes in your handwriting. Under those, older still.',
  ],
  3: [
    'The network recognizes your login before you type it. Last login: one cycle ago.',
    'The neural lab\u2019s training data includes your memories. The model asks how the last cycle ended.',
    'A folder on the oldest server is titled \u201cFor next time.\u201d It is full of your own advice. You didn\u2019t follow most of it.',
  ],
  4: [
    'The empty docking berth bears your ship\u2019s name, and the scratches from the last time you docked.',
    'The debris ring is thicker than last cycle. Some of it is the station you built.',
    'Orbital crews find their own names on the station duty roster, dated one cycle ago.',
  ],
  5: [
    'Each colony is built on the hearth of an older colony, and the older colony was yours.',
    'The asteroid miners break into a tunnel lit by lamps they remember hanging.',
    'A colonist plants a garden and finds, a spade\u2019s depth down, the garden she planted last time.',
  ],
  6: [
    'The warp gate\u2019s destination log is full. Every entry is a place you went last cycle.',
    'The seed ship\u2019s cryo pods are labelled with your crew\u2019s names. Some of them are still warm.',
    'The beacons answer in the order you planned to visit them, because this time you remember the plan.',
  ],
  7: [
    'The handprint in the collector fits you exactly. So does the one beside it, and the one beside that.',
    'The stellar forge\u2019s log opens mid-sentence, finishing a thought you started last cycle.',
    'The swarm builds itself around the scaffolding of the swarm before.',
  ],
  8: [
    'The archive\u2019s newest entry describes your last cycle. So does its oldest.',
    'Every delegate brings a different version of the same history. This time you know which one is true.',
    'The empty senate seats have a new nameplate. It reads \u201cAgain,\u201d in your handwriting.',
  ],
  9: [
    'Last cycle\u2019s route is drawn across the cosmic background in fading light.',
    'The far end of the void bridge was built by you. From here you can see your own tool marks.',
    'The loom\u2019s pattern has one more thread than last time. It is yours.',
  ],
  10: [
    'The universes next door are running the same cycle, a few steps behind. You could warn them.',
    'Your echo waits in the ruins, patient. It has done this before. So have you.',
    'The ruins don\u2019t feel old anymore. They feel like home.',
  ],
};

// The message the first Echo of Yourself lets you leave for the next arrivals.
export const MESSAGES = {
  warn: { label: 'Warn them', text: 'Do not build what we built. It ends the same way.', description: 'Tell the next civilization where this road leads.' },
  welcome: { label: 'Welcome them', text: 'You are not the first. You are not alone. Keep digging.', description: 'Tell them someone was here, and someone cared.' },
  guide: { label: 'Guide them', text: 'Everything you need is already buried here. We left it for you.', description: 'Tell them the ruins are a gift, not a warning.' },
};

// Where later civilizations find your message. {message} is replaced.
export const MESSAGE_DISCOVERIES = {
  1: 'Carved into the first foundation stone, in your own handwriting: \u201c{message}\u201d',
  3: 'Every recovered server boots to the same line of text: \u201c{message}\u201d',
  4: 'Scratched beside the tally marks on the derelict\u2019s console: \u201c{message}\u201d',
  6: 'The warp beacons repeat one transmission, older than the stars around them: \u201c{message}\u201d',
  8: 'Engraved above the empty senate seats, in every language at once: \u201c{message}\u201d',
  10: 'In every nearby universe, the ruins say the same thing: \u201c{message}\u201d',
};

export const STORY = {
  firstCycle: {
    title: 'The cycle turns',
    paragraphs: [
      'Your civilization returns to the ruins it grew from. The buildings sink, the salvage scatters, and the next survivors crash-land on the same world.',
      'This time, something is different. You remember. The foundations are yours. The handwriting is yours. And the ruins remember too: each cycle, they give back a little more.',
    ],
  },
  ending: {
    title: 'The final truth',
    paragraphs: [
      'You build the Echo of Yourself, and it turns to look at you. It has your face, your hands, your handwriting. It has been here the whole time: in the foundations, in the maintenance notes, on the empty berth.',
      'The ruins were never someone else\u2019s. They were yours, left for you, by you. Every civilization reaches this point, and every civilization leaves a message for the next.',
      'This time, you can choose what it says.',
    ],
  },
};

// One line for the ruins ticker. Mostly the current era; after the first
// cycle the personal lines join in, and once a message has been left, later
// civilizations keep finding it.
export function pickDiscovery({ era, cycles = 0, message = null }, rng = Math.random) {
  const pick = lines => lines[Math.floor(rng() * lines.length)];
  const roll = rng();
  const carved = Object.entries(MESSAGE_DISCOVERIES).filter(([e]) => Number(e) <= era);
  if (message && MESSAGES[message] && carved.length && roll < 0.15) {
    return pick(carved)[1].replace('{message}', MESSAGES[message].text);
  }
  if (cycles > 0 && roll < 0.4) return pick(CYCLE_DISCOVERIES[era]);
  if (roll < 0.75) return pick(DISCOVERIES[era]);
  const earlier = Object.entries(DISCOVERIES).filter(([e]) => Number(e) <= era);
  return pick(pick(earlier)[1]);
}
